insert into public.assets (symbol, provider_symbol, name, sector, country, currency, kind, us_symbol, us_factor, coingecko_id, active) values
('AAPL', 'AAPL', 'Apple', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('MSFT', 'MSFT', 'Microsoft', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('NVDA', 'NVDA', 'NVIDIA', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('GOOGL', 'GOOGL', 'Alphabet', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('AMZN', 'AMZN', 'Amazon', 'Commerce en ligne', 'US', 'USD', 'stock', null, null, null, true),
('META', 'META', 'Meta Platforms', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('TSLA', 'TSLA', 'Tesla', 'Automobile', 'US', 'USD', 'stock', null, null, null, true),
('AMD', 'AMD', 'AMD', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('AVGO', 'AVGO', 'Broadcom', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('INTC', 'INTC', 'Intel', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('QCOM', 'QCOM', 'Qualcomm', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('MU', 'MU', 'Micron', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('TXN', 'TXN', 'Texas Instruments', 'Semi-conducteurs', 'US', 'USD', 'stock', null, null, null, true),
('ORCL', 'ORCL', 'Oracle', 'Logiciels', 'US', 'USD', 'stock', null, null, null, true),
('CRM', 'CRM', 'Salesforce', 'Logiciels', 'US', 'USD', 'stock', null, null, null, true),
('ADBE', 'ADBE', 'Adobe', 'Logiciels', 'US', 'USD', 'stock', null, null, null, true),
('PLTR', 'PLTR', 'Palantir', 'Logiciels', 'US', 'USD', 'stock', null, null, null, true),
('IBM', 'IBM', 'IBM', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('CSCO', 'CSCO', 'Cisco', 'Technologie', 'US', 'USD', 'stock', null, null, null, true),
('NFLX', 'NFLX', 'Netflix', 'Médias', 'US', 'USD', 'stock', null, null, null, true),
('DIS', 'DIS', 'Disney', 'Médias', 'US', 'USD', 'stock', null, null, null, true),
('TTWO', 'TTWO', 'Take-Two Interactive', 'Jeux vidéo', 'US', 'USD', 'stock', null, null, null, true),
('RBLX', 'RBLX', 'Roblox', 'Jeux vidéo', 'US', 'USD', 'stock', null, null, null, true),
('UBER', 'UBER', 'Uber', 'Transport', 'US', 'USD', 'stock', null, null, null, true),
('ABNB', 'ABNB', 'Airbnb', 'Tourisme', 'US', 'USD', 'stock', null, null, null, true),
('DAL', 'DAL', 'Delta Air Lines', 'Transport', 'US', 'USD', 'stock', null, null, null, true),
('UPS', 'UPS', 'UPS', 'Transport', 'US', 'USD', 'stock', null, null, null, true),
('JPM', 'JPM', 'JPMorgan Chase', 'Banque', 'US', 'USD', 'stock', null, null, null, true),
('BAC', 'BAC', 'Bank of America', 'Banque', 'US', 'USD', 'stock', null, null, null, true),
('GS', 'GS', 'Goldman Sachs', 'Banque', 'US', 'USD', 'stock', null, null, null, true),
('MS', 'MS', 'Morgan Stanley', 'Banque', 'US', 'USD', 'stock', null, null, null, true),
('BRK.B', 'BRK.B', 'Berkshire Hathaway', 'Assurance', 'US', 'USD', 'stock', null, null, null, true),
('V', 'V', 'Visa', 'Paiements', 'US', 'USD', 'stock', null, null, null, true),
('MA', 'MA', 'Mastercard', 'Paiements', 'US', 'USD', 'stock', null, null, null, true),
('PYPL', 'PYPL', 'PayPal', 'Paiements', 'US', 'USD', 'stock', null, null, null, true),
('COIN', 'COIN', 'Coinbase', 'Paiements', 'US', 'USD', 'stock', null, null, null, true),
('WMT', 'WMT', 'Walmart', 'Distribution', 'US', 'USD', 'stock', null, null, null, true),
('COST', 'COST', 'Costco', 'Distribution', 'US', 'USD', 'stock', null, null, null, true),
('HD', 'HD', 'Home Depot', 'Distribution', 'US', 'USD', 'stock', null, null, null, true),
('MCD', 'MCD', 'McDonald''s', 'Restauration', 'US', 'USD', 'stock', null, null, null, true),
('SBUX', 'SBUX', 'Starbucks', 'Restauration', 'US', 'USD', 'stock', null, null, null, true),
('NKE', 'NKE', 'Nike', 'Habillement', 'US', 'USD', 'stock', null, null, null, true),
('KO', 'KO', 'Coca-Cola', 'Boissons', 'US', 'USD', 'stock', null, null, null, true),
('PEP', 'PEP', 'PepsiCo', 'Boissons', 'US', 'USD', 'stock', null, null, null, true),
('PG', 'PG', 'Procter & Gamble', 'Consommation', 'US', 'USD', 'stock', null, null, null, true),
('JNJ', 'JNJ', 'Johnson & Johnson', 'Santé', 'US', 'USD', 'stock', null, null, null, true),
('LLY', 'LLY', 'Eli Lilly', 'Santé', 'US', 'USD', 'stock', null, null, null, true),
('PFE', 'PFE', 'Pfizer', 'Santé', 'US', 'USD', 'stock', null, null, null, true),
('MRK', 'MRK', 'Merck & Co.', 'Santé', 'US', 'USD', 'stock', null, null, null, true),
('UNH', 'UNH', 'UnitedHealth', 'Santé', 'US', 'USD', 'stock', null, null, null, true),
('BA', 'BA', 'Boeing', 'Aéronautique', 'US', 'USD', 'stock', null, null, null, true),
('GE', 'GE', 'GE Aerospace', 'Aéronautique', 'US', 'USD', 'stock', null, null, null, true),
('LMT', 'LMT', 'Lockheed Martin', 'Défense', 'US', 'USD', 'stock', null, null, null, true),
('RTX', 'RTX', 'RTX', 'Défense', 'US', 'USD', 'stock', null, null, null, true),
('CAT', 'CAT', 'Caterpillar', 'Industrie', 'US', 'USD', 'stock', null, null, null, true),
('F', 'F', 'Ford', 'Automobile', 'US', 'USD', 'stock', null, null, null, true),
('GM', 'GM', 'General Motors', 'Automobile', 'US', 'USD', 'stock', null, null, null, true),
('T', 'T', 'AT&T', 'Télécoms', 'US', 'USD', 'stock', null, null, null, true),
('VZ', 'VZ', 'Verizon', 'Télécoms', 'US', 'USD', 'stock', null, null, null, true),
('XOM', 'XOM', 'ExxonMobil', 'Énergie', 'US', 'USD', 'stock', null, null, null, true),
('CVX', 'CVX', 'Chevron', 'Énergie', 'US', 'USD', 'stock', null, null, null, true),
('NEE', 'NEE', 'NextEra Energy', 'Énergie', 'US', 'USD', 'stock', null, null, null, true),
('ASML', 'ASML', 'ASML', 'Semi-conducteurs', 'NL', 'USD', 'stock', null, null, null, true),
('MC', 'LVMUY', 'LVMH', 'Luxe', 'FR', 'USD', 'stock', 'LVMUY', 5, null, true),
('RMS', 'HESAY', 'Hermès', 'Luxe', 'FR', 'USD', 'stock', 'HESAY', 10, null, true),
('KER', 'PPRUY', 'Kering', 'Luxe', 'FR', 'USD', 'stock', 'PPRUY', 10, null, true),
('OR', 'LRLCY', 'L''Oréal', 'Consommation', 'FR', 'USD', 'stock', 'LRLCY', 5, null, true),
('BN', 'DANOY', 'Danone', 'Consommation', 'FR', 'USD', 'stock', 'DANOY', 5, null, true),
('RI', 'PDRDY', 'Pernod Ricard', 'Boissons', 'FR', 'USD', 'stock', 'PDRDY', 5, null, true),
('TTE', 'TTE', 'TotalEnergies', 'Énergie', 'FR', 'USD', 'stock', 'TTE', 1, null, true),
('ENGI', 'ENGIY', 'Engie', 'Énergie', 'FR', 'USD', 'stock', 'ENGIY', 1, null, true),
('AIR', 'EADSY', 'Airbus', 'Aéronautique', 'FR', 'USD', 'stock', 'EADSY', 4, null, true),
('SAF', 'SAFRY', 'Safran', 'Aéronautique', 'FR', 'USD', 'stock', 'SAFRY', 4, null, true),
('SAN', 'SNY', 'Sanofi', 'Santé', 'FR', 'USD', 'stock', 'SNY', 2, null, true),
('EL', 'ESLOY', 'EssilorLuxottica', 'Santé', 'FR', 'USD', 'stock', 'ESLOY', 2, null, true),
('AI', 'AIQUY', 'Air Liquide', 'Chimie', 'FR', 'USD', 'stock', 'AIQUY', 5, null, true),
('SU', 'SBGSY', 'Schneider Electric', 'Industrie', 'FR', 'USD', 'stock', 'SBGSY', 5, null, true),
('DG', 'VCISY', 'Vinci', 'Construction', 'FR', 'USD', 'stock', 'VCISY', 4, null, true),
('BNP', 'BNPQY', 'BNP Paribas', 'Banque', 'FR', 'USD', 'stock', 'BNPQY', 2, null, true),
('GLE', 'SCGLY', 'Société Générale', 'Banque', 'FR', 'USD', 'stock', 'SCGLY', 5, null, true),
('CS', 'AXAHY', 'AXA', 'Assurance', 'FR', 'USD', 'stock', 'AXAHY', 1, null, true),
('ORA', 'ORANY', 'Orange', 'Télécoms', 'FR', 'USD', 'stock', 'ORANY', 1, null, true),
('CAP', 'CGEMY', 'Capgemini', 'Technologie', 'FR', 'USD', 'stock', 'CGEMY', 5, null, true),
('DSY', 'DASTY', 'Dassault Systèmes', 'Logiciels', 'FR', 'USD', 'stock', 'DASTY', 1, null, true),
('RNO', 'RNLSY', 'Renault', 'Automobile', 'FR', 'USD', 'stock', 'RNLSY', 5, null, true),
('UBI', 'UBSFY', 'Ubisoft', 'Jeux vidéo', 'FR', 'USD', 'stock', 'UBSFY', 5, null, true),
('SAP', 'SAP', 'SAP', 'Logiciels', 'DE', 'USD', 'stock', 'SAP', 1, null, true),
('SIE', 'SIEGY', 'Siemens', 'Industrie', 'DE', 'USD', 'stock', 'SIEGY', 2, null, true),
('ALV', 'ALIZY', 'Allianz', 'Assurance', 'DE', 'USD', 'stock', 'ALIZY', 10, null, true),
('ADS', 'ADDYY', 'Adidas', 'Habillement', 'DE', 'USD', 'stock', 'ADDYY', 2, null, true),
('VOW3', 'VWAGY', 'Volkswagen', 'Automobile', 'DE', 'USD', 'stock', 'VWAGY', 10, null, true),
('BMW', 'BMWYY', 'BMW', 'Automobile', 'DE', 'USD', 'stock', 'BMWYY', 3, null, true),
('MBG', 'MBGYY', 'Mercedes-Benz', 'Automobile', 'DE', 'USD', 'stock', 'MBGYY', 4, null, true),
('DBK', 'DB', 'Deutsche Bank', 'Banque', 'DE', 'USD', 'stock', 'DB', 1, null, true),
('BAYN', 'BAYRY', 'Bayer', 'Santé', 'DE', 'USD', 'stock', 'BAYRY', 4, null, true),
('IFX', 'IFNNY', 'Infineon', 'Semi-conducteurs', 'DE', 'USD', 'stock', 'IFNNY', 1, null, true),
('DTE', 'DTEGY', 'Deutsche Telekom', 'Télécoms', 'DE', 'USD', 'stock', 'DTEGY', 1, null, true),
('RHM', 'RNMBY', 'Rheinmetall', 'Défense', 'DE', 'USD', 'stock', 'RNMBY', 5, null, true),
('STLA', 'STLA', 'Stellantis', 'Automobile', 'NL', 'USD', 'stock', null, null, null, true),
('PHIA', 'PHG', 'Philips', 'Santé', 'NL', 'USD', 'stock', 'PHG', 1, null, true),
('INGA', 'ING', 'ING', 'Banque', 'NL', 'USD', 'stock', 'ING', 1, null, true),
('HEIA', 'HEINY', 'Heineken', 'Boissons', 'NL', 'USD', 'stock', 'HEINY', 2, null, true),
('ADYEN', 'ADYEY', 'Adyen', 'Paiements', 'NL', 'USD', 'stock', 'ADYEY', 100, null, true),
('NESN', 'NSRGY', 'Nestlé', 'Consommation', 'CH', 'USD', 'stock', 'NSRGY', 1, null, true),
('ROG', 'RHHBY', 'Roche', 'Santé', 'CH', 'USD', 'stock', 'RHHBY', 8, null, true),
('NOVN', 'NVS', 'Novartis', 'Santé', 'CH', 'USD', 'stock', 'NVS', 1, null, true),
('UBSG', 'UBS', 'UBS', 'Banque', 'CH', 'USD', 'stock', 'UBS', 1, null, true),
('SHEL', 'SHEL', 'Shell', 'Énergie', 'GB', 'USD', 'stock', 'SHEL', 0.5, null, true),
('BP', 'BP', 'BP', 'Énergie', 'GB', 'USD', 'stock', 'BP', 0.166667, null, true),
('HSBA', 'HSBC', 'HSBC', 'Banque', 'GB', 'USD', 'stock', 'HSBC', 0.2, null, true),
('ULVR', 'UL', 'Unilever', 'Consommation', 'GB', 'USD', 'stock', 'UL', 1, null, true),
('AZN', 'AZN', 'AstraZeneca', 'Santé', 'GB', 'USD', 'stock', null, null, null, true),
('GSK', 'GSK', 'GSK', 'Santé', 'GB', 'USD', 'stock', 'GSK', 0.5, null, true),
('DGE', 'DEO', 'Diageo', 'Boissons', 'GB', 'USD', 'stock', 'DEO', 0.25, null, true),
('RIO', 'RIO', 'Rio Tinto', 'Mines', 'GB', 'USD', 'stock', null, null, null, true),
('ARM', 'ARM', 'Arm Holdings', 'Semi-conducteurs', 'GB', 'USD', 'stock', null, null, null, true),
('NOVO', 'NVO', 'Novo Nordisk', 'Santé', 'DK', 'USD', 'stock', 'NVO', 1, null, true),
('SPOT', 'SPOT', 'Spotify', 'Médias', 'SE', 'USD', 'stock', null, null, null, true),
('ERIC', 'ERIC', 'Ericsson', 'Télécoms', 'SE', 'USD', 'stock', null, null, null, true),
('NOK', 'NOK', 'Nokia', 'Télécoms', 'FI', 'USD', 'stock', null, null, null, true),
('EQNR', 'EQNR', 'Equinor', 'Énergie', 'NO', 'USD', 'stock', null, null, null, true),
('RACE', 'RACE', 'Ferrari', 'Automobile', 'IT', 'USD', 'stock', null, null, null, true),
('ENI', 'E', 'Eni', 'Énergie', 'IT', 'USD', 'stock', 'E', 0.5, null, true),
('SANT', 'SAN', 'Banco Santander', 'Banque', 'ES', 'USD', 'stock', 'SAN', 1, null, true),
('ITX', 'IDEXY', 'Inditex', 'Habillement', 'ES', 'USD', 'stock', 'IDEXY', 2, null, true),
('IBE', 'IBDRY', 'Iberdrola', 'Énergie', 'ES', 'USD', 'stock', 'IBDRY', 0.25, null, true),
('TSM', 'TSM', 'TSMC', 'Semi-conducteurs', 'TW', 'USD', 'stock', null, null, null, true),
('SONY', 'SONY', 'Sony', 'Électronique', 'JP', 'USD', 'stock', null, null, null, true),
('NTDOY', 'NTDOY', 'Nintendo', 'Jeux vidéo', 'JP', 'USD', 'stock', null, null, null, true),
('TM', 'TM', 'Toyota', 'Automobile', 'JP', 'USD', 'stock', null, null, null, true),
('HMC', 'HMC', 'Honda', 'Automobile', 'JP', 'USD', 'stock', null, null, null, true),
('MUFG', 'MUFG', 'Mitsubishi UFJ', 'Banque', 'JP', 'USD', 'stock', null, null, null, true),
('BABA', 'BABA', 'Alibaba', 'Commerce en ligne', 'CN', 'USD', 'stock', null, null, null, true),
('PDD', 'PDD', 'PDD Holdings (Temu)', 'Commerce en ligne', 'CN', 'USD', 'stock', null, null, null, true),
('JD', 'JD', 'JD.com', 'Commerce en ligne', 'CN', 'USD', 'stock', null, null, null, true),
('TCEHY', 'TCEHY', 'Tencent', 'Jeux vidéo', 'CN', 'USD', 'stock', null, null, null, true),
('BIDU', 'BIDU', 'Baidu', 'Technologie', 'CN', 'USD', 'stock', null, null, null, true),
('NIO', 'NIO', 'NIO', 'Automobile', 'CN', 'USD', 'stock', null, null, null, true),
('INFY', 'INFY', 'Infosys', 'Technologie', 'IN', 'USD', 'stock', null, null, null, true),
('HDB', 'HDB', 'HDFC Bank', 'Banque', 'IN', 'USD', 'stock', null, null, null, true),
('SE', 'SE', 'Sea Limited', 'Commerce en ligne', 'SG', 'USD', 'stock', null, null, null, true),
('SHOP', 'SHOP', 'Shopify', 'Commerce en ligne', 'CA', 'USD', 'stock', null, null, null, true),
('RY', 'RY', 'Royal Bank of Canada', 'Banque', 'CA', 'USD', 'stock', null, null, null, true),
('ENB', 'ENB', 'Enbridge', 'Énergie', 'CA', 'USD', 'stock', null, null, null, true),
('MELI', 'MELI', 'MercadoLibre', 'Commerce en ligne', 'AR', 'USD', 'stock', null, null, null, true),
('NU', 'NU', 'Nubank', 'Banque', 'BR', 'USD', 'stock', null, null, null, true),
('VALE', 'VALE', 'Vale', 'Mines', 'BR', 'USD', 'stock', null, null, null, true),
('PBR', 'PBR', 'Petrobras', 'Énergie', 'BR', 'USD', 'stock', null, null, null, true),
('BHP', 'BHP', 'BHP', 'Mines', 'AU', 'USD', 'stock', null, null, null, true),
('SPY', 'SPY', 'ETF S&P 500', 'Indice', 'US', 'USD', 'etf', null, null, null, true),
('QQQ', 'QQQ', 'ETF Nasdaq 100', 'Indice', 'US', 'USD', 'etf', null, null, null, true),
('DIA', 'DIA', 'ETF Dow Jones', 'Indice', 'US', 'USD', 'etf', null, null, null, true),
('IWM', 'IWM', 'ETF Russell 2000 (petites entreprises)', 'Indice', 'US', 'USD', 'etf', null, null, null, true),
('VTI', 'VTI', 'ETF marché américain total', 'Indice', 'US', 'USD', 'etf', null, null, null, true),
('CAC', 'CAC.PA', 'ETF CAC 40', 'Indice', 'FR', 'EUR', 'etf', null, null, null, false),
('EWQ', 'EWQ', 'ETF MSCI France', 'Pays', 'FR', 'USD', 'etf', null, null, null, true),
('EWG', 'EWG', 'ETF MSCI Allemagne', 'Pays', 'DE', 'USD', 'etf', null, null, null, true),
('EWU', 'EWU', 'ETF MSCI Royaume-Uni', 'Pays', 'GB', 'USD', 'etf', null, null, null, true),
('VGK', 'VGK', 'ETF Europe', 'Pays', 'EU', 'USD', 'etf', null, null, null, true),
('EFA', 'EFA', 'ETF pays développés hors États-Unis', 'Pays', 'WW', 'USD', 'etf', null, null, null, true),
('EEM', 'EEM', 'ETF marchés émergents', 'Pays', 'WW', 'USD', 'etf', null, null, null, true),
('EWJ', 'EWJ', 'ETF MSCI Japon', 'Pays', 'JP', 'USD', 'etf', null, null, null, true),
('FXI', 'FXI', 'ETF grandes entreprises chinoises', 'Pays', 'CN', 'USD', 'etf', null, null, null, true),
('INDA', 'INDA', 'ETF MSCI Inde', 'Pays', 'IN', 'USD', 'etf', null, null, null, true),
('EWZ', 'EWZ', 'ETF MSCI Brésil', 'Pays', 'BR', 'USD', 'etf', null, null, null, true),
('XLK', 'XLK', 'ETF secteur technologie', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('SOXX', 'SOXX', 'ETF semi-conducteurs', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('XLF', 'XLF', 'ETF secteur financier', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('XLE', 'XLE', 'ETF secteur énergie', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('XLV', 'XLV', 'ETF secteur santé', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('ITA', 'ITA', 'ETF aéronautique et défense', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('ICLN', 'ICLN', 'ETF énergie propre', 'Sectoriel', 'WW', 'USD', 'etf', null, null, null, true),
('ARKK', 'ARKK', 'ETF ARK Innovation', 'Sectoriel', 'US', 'USD', 'etf', null, null, null, true),
('TLT', 'TLT', 'ETF obligations d''État américaines 20 ans et +', 'Obligations', 'US', 'USD', 'etf', null, null, null, true),
('GLD', 'GLD', 'Or', 'Métaux précieux', 'WW', 'USD', 'commodity', null, null, null, true),
('SLV', 'SLV', 'Argent', 'Métaux précieux', 'WW', 'USD', 'commodity', null, null, null, true),
('PPLT', 'PPLT', 'Platine', 'Métaux précieux', 'WW', 'USD', 'commodity', null, null, null, true),
('CPER', 'CPER', 'Cuivre', 'Métaux industriels', 'WW', 'USD', 'commodity', null, null, null, true),
('USO', 'USO', 'Pétrole WTI', 'Énergie', 'WW', 'USD', 'commodity', null, null, null, true),
('BNO', 'BNO', 'Pétrole Brent', 'Énergie', 'WW', 'USD', 'commodity', null, null, null, true),
('UNG', 'UNG', 'Gaz naturel', 'Énergie', 'WW', 'USD', 'commodity', null, null, null, true),
('URA', 'URA', 'Uranium (mines)', 'Énergie', 'WW', 'USD', 'commodity', null, null, null, true),
('DBA', 'DBA', 'Agriculture (panier)', 'Agriculture', 'WW', 'USD', 'commodity', null, null, null, true),
('WEAT', 'WEAT', 'Blé', 'Agriculture', 'WW', 'USD', 'commodity', null, null, null, true),
('CORN', 'CORN', 'Maïs', 'Agriculture', 'WW', 'USD', 'commodity', null, null, null, true),
('SOYB', 'SOYB', 'Soja', 'Agriculture', 'WW', 'USD', 'commodity', null, null, null, true),
('BTC', 'CG:bitcoin', 'Bitcoin', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'bitcoin', true),
('ETH', 'CG:ethereum', 'Ethereum', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'ethereum', true),
('SOL', 'CG:solana', 'Solana', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'solana', true),
('XRP', 'CG:ripple', 'XRP', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'ripple', true),
('BNB', 'CG:binancecoin', 'BNB', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'binancecoin', true),
('DOGE', 'CG:dogecoin', 'Dogecoin', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'dogecoin', true),
('ADA', 'CG:cardano', 'Cardano', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'cardano', true),
('AVAX', 'CG:avalanche-2', 'Avalanche', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'avalanche-2', true),
('LINK', 'CG:chainlink', 'Chainlink', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'chainlink', true),
('DOT', 'CG:polkadot', 'Polkadot', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'polkadot', true),
('LTC', 'CG:litecoin', 'Litecoin', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'litecoin', true),
('TRX', 'CG:tron', 'TRON', 'Cryptomonnaie', 'WW', 'EUR', 'crypto', null, null, 'tron', true)
on conflict (symbol) do update set
  provider_symbol = excluded.provider_symbol, name = excluded.name, sector = excluded.sector, country = excluded.country,
  currency = excluded.currency, kind = excluded.kind, us_symbol = excluded.us_symbol, us_factor = excluded.us_factor,
  coingecko_id = excluded.coingecko_id, active = excluded.active;
update public.assets set active = false where symbol not in ('AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AMD', 'AVGO', 'INTC', 'QCOM', 'MU', 'TXN', 'ORCL', 'CRM', 'ADBE', 'PLTR', 'IBM', 'CSCO', 'NFLX', 'DIS', 'TTWO', 'RBLX', 'UBER', 'ABNB', 'DAL', 'UPS', 'JPM', 'BAC', 'GS', 'MS', 'BRK.B', 'V', 'MA', 'PYPL', 'COIN', 'WMT', 'COST', 'HD', 'MCD', 'SBUX', 'NKE', 'KO', 'PEP', 'PG', 'JNJ', 'LLY', 'PFE', 'MRK', 'UNH', 'BA', 'GE', 'LMT', 'RTX', 'CAT', 'F', 'GM', 'T', 'VZ', 'XOM', 'CVX', 'NEE', 'ASML', 'MC', 'RMS', 'KER', 'OR', 'BN', 'RI', 'TTE', 'ENGI', 'AIR', 'SAF', 'SAN', 'EL', 'AI', 'SU', 'DG', 'BNP', 'GLE', 'CS', 'ORA', 'CAP', 'DSY', 'RNO', 'UBI', 'SAP', 'SIE', 'ALV', 'ADS', 'VOW3', 'BMW', 'MBG', 'DBK', 'BAYN', 'IFX', 'DTE', 'RHM', 'STLA', 'PHIA', 'INGA', 'HEIA', 'ADYEN', 'NESN', 'ROG', 'NOVN', 'UBSG', 'SHEL', 'BP', 'HSBA', 'ULVR', 'AZN', 'GSK', 'DGE', 'RIO', 'ARM', 'NOVO', 'SPOT', 'ERIC', 'NOK', 'EQNR', 'RACE', 'ENI', 'SANT', 'ITX', 'IBE', 'TSM', 'SONY', 'NTDOY', 'TM', 'HMC', 'MUFG', 'BABA', 'PDD', 'JD', 'TCEHY', 'BIDU', 'NIO', 'INFY', 'HDB', 'SE', 'SHOP', 'RY', 'ENB', 'MELI', 'NU', 'VALE', 'PBR', 'BHP', 'SPY', 'QQQ', 'DIA', 'IWM', 'VTI', 'CAC', 'EWQ', 'EWG', 'EWU', 'VGK', 'EFA', 'EEM', 'EWJ', 'FXI', 'INDA', 'EWZ', 'XLK', 'SOXX', 'XLF', 'XLE', 'XLV', 'ITA', 'ICLN', 'ARKK', 'TLT', 'GLD', 'SLV', 'PPLT', 'CPER', 'USO', 'BNO', 'UNG', 'URA', 'DBA', 'WEAT', 'CORN', 'SOYB', 'BTC', 'ETH', 'SOL', 'XRP', 'BNB', 'DOGE', 'ADA', 'AVAX', 'LINK', 'DOT', 'LTC', 'TRX');
